### PR TITLE
add css for medium icon

### PR DESCRIPTION
**Pull request by tincho**

### CODE REVIEW

**Comment by tincho** [comment]
Hi. I just realized this fix works for the exported HTML but the icon is seen as a square in the PDF

**Review by thibaudcolas — CHANGES_REQUESTED** [review]
@tincho 👋 

I don't see how this could work without also adding the icon in the IcoMoon project: https://github.com/thibaudcolas/jsonresume-theme-eloquent/blob/master/raw/eloquent-icomoon.json, and in the inlined icon source at the start of this file.

**Comment by tincho** [comment]
Hi! the web version shows the icon only adding that content property. Could you please help me out a little  more with the generation of the inlined icon data-uri src: property? Thanks!

**Comment by thibaudcolas** [comment]
Sure! Here are the rough steps to add new icons:

1. Go to IcoMoon https://icomoon.io/app/#/projects
2. Load the "eloquent" project: https://github.com/thibaudcolas/jsonresume-theme-eloquent/blob/master/raw/eloquent-icomoon.json
3. Find and select the icon you want to add (say "Medium")
4. Export the project JSON and update it in `eloquent-icomoon.json` with the icon added.
5. Download the generated icon files from IcoMoon
6. Make a data URI of the `.woff` file
7. Update the data URI at the top of `icomoon.css` with the new one.

**Review by thibaudcolas — APPROVED** [review]
👌thank you, looks good to me!

**Comment by thibaudcolas** [comment]
Now available on npm as v4.1.0 😃

**Pull request merged**
